### ISSUE TITLE
Does WebView Allow Ajax Requests

### ISSUE THREAD

**Issue by morgan4080** [MohamedRejeb/Calf#10]
I was googling around and found 
`val settings: WebSettings = webview.getSettings();
        settings.setJavaScriptEnabled(true);
        settings.setDomStorageEnabled(true);`
        
I wonder if this is already enabled on Calf Webview?
 I get a blank page with this link which has a lot of xhr/ajax 
`https://sign.zoho.com/zsguest?locale=en&sign_id=234b4d535f495623eec545575b5ff767ae2cc1e50a5a4796a2cc40020ee8d185a971f31d96a1fb6037de65f4cce9f392ee2b84979ecb3fbcc65fbd768ffb4e13b63f8686a679e74500c52b2c1c7ee71e6994e5ae3aea726b35e4e8349d52292309d6563503131e960c9cce171f03a00ce0dce08c895ca6f37114f8a37c301a5dcd471d8269730db4&frameorigin=https://presta.co.ke`

**Comment by MohamedRejeb** [comment]
With calf-ui 0.2.0 you can enable javascript and you can call javascript code as well.

```kotlin
state.settings.javaScriptEnabled = true
state.evaluateJavascript(
    """
        jsCode();
    """.trimIndent()
) {
    println("JS result: $it")
}
```
