### ISSUE TITLE
 rememberSheetState uses confirmValueChange as an input resulting in losing sheet state 

### ISSUE THREAD

**Issue by ZacSweers** [MohamedRejeb/Calf#116]
Analogous to https://issuetracker.google.com/issues/355061541 but this issue exists in this library's `AdaptiveBottomSheet` as well due to its use of the same pattern.

**Comment by MohamedRejeb** [comment]
I think this is the best solution with fewer recompositions, what do you think:

```kotlin
private class SheetValueHolder(
    var value: SheetValue
)

@Composable
fun rememberAdaptiveSheetState(
    skipPartiallyExpanded: Boolean = false,
    confirmValueChange: (SheetValue) -> Boolean = { true },
): AdaptiveSheetState {
    val sheetValueHolder = remember {
        SheetValueHolder(SheetValue.Hidden)
    }

    val state = rememberSaveable(
        skipPartiallyExpanded,
        confirmValueChange,
        saver = AdaptiveSheetState.Saver(
            skipPartiallyExpanded = skipPartiallyExpanded,
            confirmValueChange = confirmValueChange
        )
    ) {
        AdaptiveSheetState(skipPartiallyExpanded, sheetValueHolder.value, confirmValueChange)
    }


    LaunchedEffect(state.currentValue) {
        sheetValueHolder.value = state.currentValue
    }

    return state
}
```

**Comment by ZacSweers** [comment]
I don't think that's quite enough actually. The primary issue at the moment is actually the `confirmValueChange` lambda, which has a bug and isn't memoized in kotlin 2.0.0 and triggers this

**Comment by MohamedRejeb** [comment]
I will try `confirmValueChange`, what I tried is changing `skipPartiallyExpanded` and the sheet value was changed to `Hidden` and then changed back to `HalfExpanded` or `Expanded` depends on the value of `skipPartiallyExpanded`.
After this change, the sheet value stays correct.
