### ISSUE TITLE
AdaptiveDatePicker doesn't propagate colors on iOS

### ISSUE THREAD

**Issue by ZacSweers** [MohamedRejeb/Calf#122]
While it accepts `DatePickerColors` as a parameter, the iOS implementation doesn't use it. The result is the date picker is always the iOS default

<img width="740" alt="image" src="https://github.com/user-attachments/assets/07b59fcb-90d8-4d34-847a-7acc5127fddd">

![image](https://github.com/user-attachments/assets/604b9262-4f01-4e90-8390-5bb98b3c49b2)

**Comment by MohamedRejeb** [comment]
Customizing iOS native components is tricky, they don't give the same freedom as Compose.
For now what I managed to do is:
- `containerColor`: Will update the background color of the picker
- `selectedDayContentColor`: Will update the tint color
- `dayContentColor`: Currently only white and black are supported (Handled by the component theme), when you choose a color, I will look if it's more white or black and then set the theme of the date picker which will change the text color accordingly.

```kotlin
DatePickerDefaults.colors(
    selectedDayContentColor = Color.Red,
    dayContentColor = Color.DarkGray,
    containerColor = Color.LightGray
)
```

<img width="407" alt="Screenshot 2024-07-25 at 8 59 41 AM" src="https://github.com/user-attachments/assets/aa14317d-b2d3-4b99-b932-cc39b6d9f04e">

This will be available in the next release and the [snapshot](https://mohamedrejeb.github.io/Calf/installation/#snapshots) version.

**Comment by MohamedRejeb** [comment]
The tint color on iOS should be `selectedDayContainerColor` not `selectedDayContentColor`, I will change it and then you will be able to delete this condition since `selectedDayContainerColor` is the primary color by default.

https://github.com/ZacSweers/FieldSpottr/pull/26/files#diff-c263ba207ac064a923571e58dd0ae4ee321a6a3b900cfd64b2974647903dfd0fR184
