### ISSUE TITLE
Permission.Notification crash in IOS

### ISSUE THREAD

**Issue by Moozart** [MohamedRejeb/Calf#150]
koltin: v2.0.10
compose: v1.6.11
calf: v0.5.3

In android works well, but in ios when I call  

`
val notificationStatePermission = rememberPermissionState(
        permission = Permission.Notification,
        onPermissionResult = { isGranted ->

        }
    )

`

It throws an exception. ( I already added <key>NSUserNotificationsUsageDescription</key>)
 

Uncaught Kotlin exception: kotlin.IllegalStateException: Reading a state that was created after the snapshot was taken or in a snapshot that has not yet been applied

Am I doing wrong something?

**Comment by MohamedRejeb** [comment]
Thanks for reporting this issue, I'm checking it.

**Comment by Moozart** [comment]
I used this solution temporarily.
In summary: I used  MainScope().launch(Dispatchers.Main.immediate)

    @Stable
    internal actual class MutablePermissionState(
        actual override val permission: Permission,
        private val onPermissionResult: (Boolean) -> Unit,
    ) : PermissionState {
        actual constructor(
            permission: Permission,
        ) : this(permission, {})
    
        actual override var status: PermissionStatus by mutableStateOf(PermissionStatus.Denied(false))
    
        private val permissionDelegate: PermissionHelper = getIOSPermission(permission)
    
        init {
            refreshPermissionStatus()
        }
    
        actual override fun launchPermissionRequest() {
            permissionDelegate.launchPermissionRequest(
                onPermissionResult = { isGranted: Boolean ->
                    onPermissionResult(isGranted)
                    // Update status on the main thread
                    updateStatus { refreshPermissionStatus() }
                }
            )
        }
    
        actual override fun openAppSettings() {
            val settingsUrl = NSURL.URLWithString(UIApplicationOpenSettingsURLString) ?: return
            UIApplication.sharedApplication.openURL(settingsUrl)
        }
    
        internal actual fun refreshPermissionStatus() {
            permissionDelegate.getPermissionStatus { status: PermissionStatus ->
                // Ensure status update is on the main thread
                updateStatus { this.status = status }
            }
        }
    
        private fun updateStatus(action: () -> Unit) {
            // Use the main dispatcher to ensure Compose state is updated correctly
            MainScope().launch(Dispatchers.Main.immediate) {
                action()
            }
        }
    }
