### ISSUE TITLE
How to understand whether permission is shouldShowRational or (AuthorizationStatusNotDetermined) on iOS

### ISSUE THREAD

**Issue by Moozart** [MohamedRejeb/Calf#154]
Thank you for your excellent effort for this libraries. I know this permission states are very complex. To determine is asking first permission or not I used NotDeterminedFlag with combined with shouldShowRational. Is it true approach? If yes please add to library, if not ok how can we know we need to navigate user to settings screen.

    override fun getPermissionStatus(onPermissionResult: (PermissionStatus) -> Unit) {
            val notificationCenter = getCurrentNotificationCenter()
            notificationCenter.getNotificationSettingsWithCompletionHandler { settings ->
                when (settings?.authorizationStatus) {
                    UNAuthorizationStatusAuthorized,
                    UNAuthorizationStatusProvisional,
                    UNAuthorizationStatusEphemeral -> onPermissionResult(PermissionStatus.Granted)
                    UNAuthorizationStatusNotDetermined -> onPermissionResult(PermissionStatus.Denied(false))
                    else -> onPermissionResult(PermissionStatus.Denied(true))
                }
            }
        }

**Comment by MohamedRejeb** [comment]
Thanks for creating this issue. I noticed this when I fixed the notification permission issue. I'm currently working on setting `shouldShowRationale` properly on iOS for the different type of permissions.

**Comment by MohamedRejeb** [comment]
I will publish a new release later today, which will contain the latest fixes.
