### ISSUE TITLE
DatePicker is cutoff on the bottom on iOS

### ISSUE THREAD

**Issue by ZacSweers** [MohamedRejeb/Calf#163]
At first I thought this was a missing padding issue, but finding that even with modifier padding on the bottom it's always cut off when the selection is the bottom row

Repro: https://github.com/ZacSweers/FieldSpottr/pull/48

![image](https://github.com/user-attachments/assets/c0ca00d4-658b-4473-b536-8b08c84d6af8)

**Comment by MohamedRejeb** [comment]
Thanks for reporting this. I will check it. 
Currently, I'm setting the size of the Composable from the UiKit component, which gets applied to the passed Modifier, which causes the cutoff when you set a padding, because the size will remain the same.
