### ISSUE TITLE
Notification Permission on Android 12 and below 

### ISSUE THREAD

**Issue by muazkadan** [MohamedRejeb/Calf#168]
First of all, I would like to thank you for your efforts in putting together this library.  

After I implemented notification permission, I tested it on Emulator on Android 14. Moreover, everything worked as expected, but when I tested it on a physical device running Android 12, the permission state acted like the device didn't grant permission and denied it. 

Here's a screenshot of the permission status if it helps: 
![image](https://github.com/user-attachments/assets/34c63d0c-a8c4-4026-bdde-99ab3c1f1f65)

**Comment by MohamedRejeb** [comment]
Thanks for reporting this, I will check it.
