### ISSUE TITLE
Permissions don't work with Android Studio Preview

### ISSUE THREAD

**Issue by eygraber** [MohamedRejeb/Calf#176]
The preview is broken because `context.findActivity` doesn't work in a Preview.

There is a similar issue with accompanist, and someone suggested a fix [there](https://github.com/google/accompanist/issues/1498#issuecomment-1584853572). Perhaps it could be incorporated into Calf.

**Comment by MohamedRejeb** [comment]
Sorry for the delay, thanks for opening this issue. I'll work on it.
