### ISSUE TITLE
Cannot open app settings on iOS when running app from xCode 16

### ISSUE THREAD

**Issue by m120786** [MohamedRejeb/Calf#187]
Getting this error:
BUG IN CLIENT OF UIKIT: The caller of UIApplication.openURL(_:) needs to migrate to the non-deprecated UIApplication.open(_:options:completionHandler:). Force returning false (NO).

**Comment by MohamedRejeb** [comment]
Hi,
Thanks for opening this issue, fixed in 0.6.0 check it out
