### ISSUE TITLE
AdaptiveDatePicker crashes on iOS when the user clicks on a day. The error message is “dateSelection]: unrecognized selector sent to instance.”

### ISSUE THREAD

**Issue by WPSeven** [MohamedRejeb/Calf#189]
calf-ui  = "0.5.5"
kotlin = "2.0.10"
compose= "1.6.11"
iOS = 18.1/17.5

When I click on the day on the calendar AdaptiveDatePicker it crashes on iOS. I’m not sure what to look for, but it works perfectly on Android.

I’ve come across some logs that show “NSInvalidArgumentException,” and I’m not too familiar with iOS. Could you please suggest someone who might be able to help me out?

<img width="771" alt="Screenshot 2024-10-30 at 4 46 30 PM" src="https://github.com/user-attachments/assets/0d4b9e94-aefb-4dfb-8234-0c584c2a450b">
<img width="1086" alt="Screenshot 2024-10-30 at 4 44 08 PM" src="https://github.com/user-attachments/assets/a183784c-5adb-4aca-85b5-3e3985d9211c">

**Comment by MohamedRejeb** [comment]
Hi thanks for opening this issue,
I think that the problem is with your gradle configuration.
Do you have this line here?
https://github.com/MohamedRejeb/Calf/blob/acb2a7388a776a6f22fcf7f351868359c3113695/sample/common/build.gradle.kts#L16
