### ISSUE TITLE
Js enable in WebView

### ISSUE THREAD

**Issue by AlmecDoux** [MohamedRejeb/Calf#2]
How to include js in WebView?

**Comment by MohamedRejeb** [comment]
For now it's not possible, but I'll think about it in the next releases. We can start by providing access to the native WebView class for each platform, and you can use it to include. Also, we can provide a public common API for all platforms, but it's going to require some work.

**Comment by MohamedRejeb** [comment]
Now you can call Js in WebView

```kotlin
state.evaluateJavascript(
    """
        jsCode();
    """.trimIndent()
) {
    println("JS result: $it")
}
```

**Comment by MohamedRejeb** [comment]
Just wait for publishing the new version!
