### ISSUE TITLE
Issue with Kotlin 1.8.x and Compose 1.4.x

### ISSUE THREAD

**Issue by Lilytreasure** [MohamedRejeb/Calf#4]
The Library overwrites     val pagerState = rememberPagerState()

**Comment by MohamedRejeb** [comment]
Can you give move informations about the issue? AFAIK I'm not using pager anywhere.

**Comment by Lilytreasure** [comment]
when i add this dependencies  //api("com.mohamedrejeb.calf:calf-ui:0.1.1") in my  common main gradle  the pagerState = rememberPagerState() immediately throws an error and when  i remove the dependency the error dissapear

**Comment by MohamedRejeb** [comment]
I'll check this

**Comment by Lilytreasure** [comment]
Alright thank you

**Comment by MohamedRejeb** [comment]
It's working perfectly. I think that it's a problem with your compose version.
Was is the version of Kotlin and Compose multiplatform in your project ?

**Comment by Lilytreasure** [comment]
iam using  kotlin = "1.8.20" and  compose version = "2.0.0-compose-experimental-alpha-02"

**Comment by MohamedRejeb** [comment]
There's no Compose version like that. I think that you are talking about something else.
Anyway, you need Kotlin: 1.9.0 and Compose multiplatform: 1.5.0-beta02 or above

**Comment by Lilytreasure** [comment]
Alright  thank you very much
