### ISSUE TITLE
setDetents with UISheetPresentationControllerDetent

### ISSUE THREAD

**Issue by Gaubee** [MohamedRejeb/Calf#49]
https://github.com/MohamedRejeb/Calf/blob/6cec0de74568e7088f8a007105f4897cb1f5f3a1/calf-ui/src/iosMain/kotlin/com/mohamedrejeb/calf/ui/sheet/BottomSheetManager.kt#L64-L69

should be:
```kotlin
        listOf(
          UISheetPresentationControllerDetent.mediumDetent(),
          UISheetPresentationControllerDetent.largeDetent(),
        )
```

**Comment by MohamedRejeb** [comment]
Thank you!
I fixed it. It will be available in the next release.
