### ISSUE TITLE
File picker on Android not working as expected

### ISSUE THREAD

**Issue by iruizmar** [MohamedRejeb/Calf#51]
Easily reproducible in the sample file picker screen, the list of received files is always empty. On iOS it's working as expected.

**Comment by MohamedRejeb** [comment]
This should be fixed in the next release.

Now in android target `KmpFile` is a wrapper around `Uri` instead of `File`, because I was using a code to convert the `Uri` to a `File` which was not working all the time.

**Comment by MohamedRejeb** [comment]
@youssaka I think that your issue is related to permissions. `EACCES (Permission denied)`
Make sure that you have the correct permissions for reading files in your manifest file.

**Comment by MohamedRejeb** [comment]
This should be fixed in the latest version `0.4.0`, feel free to reopen the issue if you still have problems.
