### ISSUE TITLE
Image picker on iOS doesn't return result on main thread

### ISSUE THREAD

**Issue by iruizmar** [MohamedRejeb/Calf#53]
Not sure if this is not the expected behaviour, but for some reason `PHPicker` is [not invoking the callback function](https://github.com/MohamedRejeb/Calf/blob/9871e16509024adba74c5868849f302e739bc2a8/calf-file-picker/src/iosMain/kotlin/com.mohamedrejeb.calf.picker/FilePickerLauncher.ios.kt#L110) in the main thread.

A simple `withContext(Dispatchers.Main) {` solves it, but I don't want to open a PR until I'm sure it is wanted for it to be on the main thread or is something up to the user.

**Comment by MohamedRejeb** [comment]
Yes sure, feel free to open PR with the fix.
