### ISSUE TITLE
File Picker Support for Compose Web (Kotlin/Js)

### ISSUE THREAD

**Issue by sunildhiman90** [MohamedRejeb/Calf#57]
Hi, 

Just wanted to know Are we planning to add compose web (Kotlin/JS) support in calf file picker?

Thanks

**Comment by MohamedRejeb** [comment]
Hi,
Kotlin/JS support is added to `calf-file-picker`, it will be available in the next release.

**Comment by sunildhiman90** [comment]
Thank you @MohamedRejeb , That will be great

**Comment by MohamedRejeb** [comment]
It's available now in calf `0.4.0` supporting Kotlin/JS and Kotlin/WASM.
Check the release for more details because there are some breaking changes in the file picker.
https://github.com/MohamedRejeb/Calf/releases/tag/v0.4.0
