### ISSUE TITLE
is the webview available for the desktop?

### ISSUE THREAD

**Issue by Abhay-cloud** [MohamedRejeb/Calf#6]

**Comment by MohamedRejeb** [comment]
Hi, for now it's not available for desktop but it will be available soon, I will try to clarify this more in the documentation.

**Comment by MohamedRejeb** [comment]
Update to 0.2.0

**Comment by Abhay-cloud** [comment]
@MohamedRejeb thanks! 
can we load a html into the webview?

**Comment by MohamedRejeb** [comment]
@Abhay-cloud 
Yes you can load HTML

```
```
