### ISSUE TITLE
Allow the file picker to show only custom file extension

### ISSUE THREAD

**Issue by sschuberth** [MohamedRejeb/Calf#74]
It seems like currently there's no way to only display files matching custom extensions in the picker. In my case, I'd like only `*.json` and `*.yml` files to show up for picking. Is this a functionality that could be added?

**Comment by sschuberth** [comment]
> ```kotlin
> "application/x-yaml"
> ```

Thanks, but I guess this will also allow to select `*.yaml` whereas I really only want `*.yml`, correct?

**Comment by MohamedRejeb** [comment]
Yes, you can search for a specific mime type for that extension. I will try to add extensions support ASAP.
