### ISSUE TITLE
Bottom Sheet recomposes entire content If its slightly dragged without fully dismissing

### ISSUE THREAD

**Issue by nilufer32** [MohamedRejeb/Calf#75]
In the Adaptive Bottom Sheet specifically the iOS implementation, placing any content inside the sheet causes the content to recompose if I slightly drag the sheet downwards and let it snap back to its original height without dismissing it. What I did exactly was I used the Adaptive Bottom Sheet in my iOS module and placed a WebView inside it [also from calf]. dragging the sheet and letting it go back to its original height recomposes the webview inside which causes my webview to reload.
Here's a small code snippet:
```
AdaptiveBottomSheet(
                    onDismissRequest = {  },
                    adaptiveSheetState =
                        rememberAdaptiveSheetState(),
                ) {
                    WebView(
                        state = state,
                    )
                }
```

**Comment by nilufer32** [comment]
update: this issue arises due to jetbrains compose version 1.6.0. older versions do not have this bug. any plans to address the issue?

**Comment by MohamedRejeb** [comment]
Hi
Thanks for reporting this issue.
I will check it out.

**Comment by MohamedRejeb** [comment]
Can you try with the latest version 0.5.3, it should be fixed now.
