### ISSUE TITLE
WebView with Adaptive Sheet presentation bug

### ISSUE THREAD

**Issue by nilufer32** [MohamedRejeb/Calf#77]
When replacing the modalpresentationstyle of the bottomsheetUiViewController from popover to formsheet and using the following detents:
```
bottomSheetUIViewController.modalPresentationStyle = UIModalPresentationFormSheet
bottomSheetUIViewController.sheetPresentationController?.setDetents(
            listOf(
                UISheetPresentationControllerDetent.mediumDetent(),
                UISheetPresentationControllerDetent.largeDetent(),
            ),
        )
```
and placing a WebView inside the sheet, dragging the sheet from the medium to the large detent causes a weird flickering of the webview from the bottom [as if it were continuously resizing].

**Comment by nilufer32** [comment]
Hello,
any plans on checking out this issue? thanks

**Comment by MohamedRejeb** [comment]
Hello,
Can't reproduce this with the latest version 0.5.3, can you check it now.
