### ISSUE TITLE
Not able to pick videos [IOS]

### ISSUE THREAD

**Issue by Aakansha267** [MohamedRejeb/Calf#80]
Videos are disabled even when FilePickerFileType is set to Video for iOS

**Comment by MohamedRejeb** [comment]
Thanks for reporting this issue. I will check it.

**Comment by Aakansha267** [comment]
@MohamedRejeb any update on this issue?

**Comment by MohamedRejeb** [comment]
This should be fixed in the next release `0.5.0`
