### ISSUE TITLE
Indefinite Freeze on FilePicker launch

### ISSUE THREAD

**Issue by zhelenskiy** [MohamedRejeb/Calf#88]
MacOS 14.5 (23F79)
M2 Max
calf-file-picker = "0.4.0"

```kotlin
   val pickerLauncher = rememberFilePickerLauncher(
        type = mimeType,
        selectionMode = FilePickerSelectionMode.Single,
        onResult = { files ->
            coroutineScope.launch {
                files.firstOrNull()?.let { file ->
                    // Do something with the selected file
                    // You can get the ByteArray of the file
                    println(file.getPath(context))
//                        file.readByteArray(context)
                }
            }
        }
    )
```
On a button click I do `pickerLauncher.launch()`.

The app does not show any error, just freezes.

On iOS and Android everything works as expected.

**Comment by MohamedRejeb** [comment]
Hi,
Thanks for reporting the issue. The freeze is on desktop (MacOS) right?

**Comment by zhelenskiy** [comment]
Yes

**Comment by zhelenskiy** [comment]
It seems to be caused by https://discussions.apple.com/thread/254734186#259718773022, because it was a problem for all file dialogs. Restart helped.
